language: python
python:
  - "2.7"
before_install:
  - git clone -b cnx-master https://github.com/pumazi/velruse.git
  - pip install -e velruse --use-mirrors
  - sed -i 's/velruse/velruse==1.0.3/' setup.py
install:
  - python setup.py install
script:
  - python -m unittest discover
notifications:
  email: false
